config/routes.rb
Rails.application.routes.draw do
  
  resources :television_shows, only: [:index, :show, :new, :create] do
    resources :characters, only: [:index, :show, :new, :create]
  end
end

app/models/character.rb
class Character < ActiveRecord::Base

belongs_to :television_show

end

app/models/television_show.rb
class TelevisionShow < ActiveRecord::Base

  has_many :characters
  
  validates :title,
    presence: true,
    uniqueness: { scope: :network }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @character = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
    @tvshow = TelevisionShow.find(params[:television_show_id])
  end

  def create
    @tvshow = TelevisionShow.find(params[:television_show_id])
    @character = Character.new(character_params)
    @character.television_show_id = @television_show.id

    if @character.save
      flash[:notice] = "Success!"
      redirect_to '/television_show_character_path'
    else
      flash.now[:notice] = "Your character couldn't be saved."
      render :new
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :actor, :description, :television_show_id)
  end
end

app/controllers/television_shows_controller.rb
class TelevisionShowsController < ApplicationController
  def index
    @television_shows = TelevisionShow.all
  end

  def show
    @television_show = TelevisionShow.find(params[:id])
    @characters = Character.find(params[:id] = character.television_show_id)
  end

  def new
    @television_show = TelevisionShow.new
  end

  def create
    @television_show = TelevisionShow.new(television_show_params)

    if @television_show.save
      flash[:notice] = "Success!"
      redirect_to '/television_shows'
    else
      flash.now[:notice] = "Your movie couldn't be saved."
      render :new
    end
  end

  private

  def television_show_params
    params.require(:television_show).permit(:title, :network, :years, :synopsis)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/new.html.erb
<h3>Add A Character</h3>

<%= form_for @character, url: television_shows_path do |f| %>

<% if @character.errors.any? %>
<ul>
  <% @character.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :actor %>
  <%= f.text_field :actor %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<%= f.submit 'Submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TvShows</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/television_shows/index.html.erb
<h3>All TV Shows</h3>

<ul>
  <% @television_shows.each do |show| %>
    <li>
      <%= "#{show.title} (#{show.network})" %>
    </li>
  <% end %>
</ul>

<ul>
  <% @characters.each do |character| %>
  <li>
    <%= "#{character.name}" %>
  </li>
  <% end %>
</ul>

app/views/television_shows/new.html.erb
<h3>Add A TV Show</h3>

<%= form_for @television_show do |f| %>

  <% if @television_show.errors.any? %>
    <ul>
      <% @television_show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :network %>
    <%= f.text_field :network %>
  </div>

  <div>
    <%= f.label :years %>
    <%= f.text_field :years %>
  </div>

  <div>
    <%= f.label :synopsis %>
    <%= f.text_field :synopsis %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/television_shows/show.html.erb
<h3><%= @television_show.title %></h3>

<ul>
  <li>Network: <%= @television_show.network %></li>
  <li>Years: <%= @television_show.years %></li>
</ul>

<div>
  <%= @television_show.synopsis %>
</div>